name: GRASS GIS addon overview generator

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "15 3 * * *"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  generate-grass-overview:
    name: generate overview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate GRASS GIS overview
        run: |
            (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
              && sudo mkdir -p -m 755 /etc/apt/keyrings \
              && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
              && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
              && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
              && sudo apt update \
              && sudo apt install gh -y
            pip install -r overview-generator/requirements.txt
            python3 overview-generator/generate_grass_addon_overview.py
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public"

  deploy-grass-overview:
    name: deploy-grass-overview
    runs-on: ubuntu-latest
    needs: generate-grass-overview
    permissions:
      pages: write
      id-token: write
    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
